### PR TITLE
Metadata for scRNA-seq and RNA-seq case studies.

### PR DESCRIPTION
**Pull request by areyesq89**
I filled in the metadata for the scRNA-seq and RNA-seq datasets (as agreed with @pkimes). Let me know if this is OK and happy to correct something if needed. 

@kdkorthauer: In scDD, I saw that the null model is calculated from Bayes factor scores where the sample labels are permuted. Was not sure what to fill in the test statistic so I set them to NA. Is this correct?

### CODE REVIEW

**Comment by kdkorthauer** [comment]
The test statistic field was added for the simulations, so I think we decided to set that field to NA for all case studies.

**Comment by kdkorthauer** [comment]
It looks like most other case studies actually have test statistic entries, so I misinterpreted some discussion on Slack. I'll add test statistics to GWAS, GSA, and the scDD scRNAseq entries.

**Comment by pkimes** [comment]
Sorry - when working on the ChIPseq case studies, I realized that some of these `Rds` objects only differ by the test used (e.g. `scDD` vs. `MAST` vs. `Wilcox`) so I started adding the methods in the `TestStatistic` field to make it easier to filter/sort.

I'm planning on cleaning up rough edges (e.g. `InformativeCovariate = "Uninformative"` vs. `InformativeCovariate = "Uninformative covariate"`) over the weekend after everyone's done, so as long as it's reasonably filled in, that's great! 
Thanks!!

**Comment by areyesq89** [comment]
Another note regarding cleaning/consistency: right now the chipseq case studies have the same name (h3k4me3-promoters-benchmark), while most of the rest of the case studies have unique names.

**Comment by kdkorthauer** [comment]
@areyesq89 where do you see that? It looks like the title field and object names are different for each entry.

**Comment by pkimes** [comment]
I don't see this either.

**Comment by areyesq89** [comment]
Sorry, I meant the title slot. 

For example here:

```
> source("inst/scripts/make-casestudies-metadata.R")
> df_all_casestudies$Title[duplicated( df_all_casestudies$Title)]
[1] "cbp-csaw-benchmark"       "cbp-csaw-benchmark"       "cbp-csaw-benchmark"      
[4] "cbp-csaw-uninf-benchmark" "cbp-csaw-uninf-benchmark" "cbp-csaw-uninf-benchmark"
[7] "cbp-csaw-cov-benchmark"   "cbp-csaw-cov-benchmark"   "cbp-csaw-cov-benchmark"
```

**Comment by pkimes** [comment]
🤦‍♂️ there were a few `paste(.., collapse = ",")` calls that were missing.
Thanks!!

**Pull request merged**
